---
title: "Untitled"
author: "Jamie Ash"
date: '2022-08-16'
output: html_document
---

```{r setup, include=FALSE, message = FALSE}
source("functions.R")
source("libraries.R")
rasterOptions(maxmemory = 120e+10, memfrac = 0.9)
knitr::opts_chunk$set(echo = TRUE)
```

Custom functions 
```{r, message = FALSE}

load_nc = function(path = "C:\\Users\\james\\Desktop\\jamieslife\\data\\infiles\\fsle\\",
                   patt = "fsle_po_2018.nc", 
                   vars = c("lat", "lon", "fsle_max", "time"),
                   origin = "1950-01-01"){
  infile = paste(path, patt, sep = "")
  file  = nc_open(infile)
  lat   = ncvar_get(file, varid = "lat")
  lon   = ncvar_get(file, varid = "lon")
  ras   = ncvar_get(file, varid = "fsle_max")
  t     = ncvar_get(file, varid = "time")
  attr  = ncatt_get(file, varid = 0)
  t     = as.Date(t, origin = as.Date(origin))
  ras   = brick(ras)
  extent(ras) = extent(min(lon), max(lon), min(lat), max(lat))
  fsle  = setZ(ras, z = t, name = "time")
  fsle
}
# input is a boolian raster layer of 0/1 
# output is a data frame with only high values included
# Downlsize reduces the size of the data set
# I may like to simultaniously index the chl signal as well
# chl_fronts = function(blooms,
#                       signal,
#                       downsize = 10){
#   ras  = raster::flip(blooms, direction = "x")
# 
#   idx  = which(values(blooms) == TRUE) # == TRUE
#   
#   e    = extent(blooms)
#   s    = dim(blooms)
#   lons = seq(from = e[1], to = e[2], length = s[1]) 
#   lats = seq(from = e[3], to = e[4], length = s[2]) 
#   grid = pracma::meshgrid(lons, lats)
#   # using the blooms index to subset the signal values
#   fronts = data.frame(lons = grid$X[idx], lats = grid$Y[idx], value = signal[idx])
#   idx = seq(1, nrow(fronts), downsize)
#   fronts = fronts[idx, ]
#   fronts
# }

# use the apply function to apply the calc mean function for every 8 layers

avestack = function(ras, by = 8, fun){
  s      = dim(ras)
  idx_8d = rep(1:ceiling(s[3]/8), 8)
  idx_8d = sort(idx_8d)
  rem    = abs(s[3] - length(idx_8d))
  idx_8d = idx_8d[1:(length(idx_8d)-rem)]
  idx_og = 1:s[3]
  idx    = data.frame(idx_8d = idx_8d, idx_og = idx_og)
  idx$idx_8d = as.factor(idx$idx_8d)
  idx = split(idx, idx_8d)
  
  # subset and average every eight days
  tempset = function(x, ras) ras[[x$idx_og]]
  days = lapply(idx, FUN = tempset, ras = ras)
  days = lapply(days, FUN = calc, fun = fun, na.rm = TRUE)
  days
}

# ------------------------------------------------------------------------------
# input is a raster output is a boolian raster of bloom/not bloom
bool = function(x){
  u <- calc(x, fun = median, na.rm = TRUE)
  o <- calc(x, fun = mad, na.rm = TRUE)
  boo <- x > (u + o)
  extent(boo) <- extent(x)
  boo <- setZ(boo, z = getZ(x), name = "time")
  boo
}

# ------------------------------------------------------------------------------
jamie_theme <- function(x,
                        y, 
                        mar = c(1,1,1,1),
                        line = 0.75,
                        adj = 0,
                        #asp = 1,
                        ylim = range(y),
                        xlim = range(x),
                        main = "",
                        dt = TRUE,
                        ylab = "",
                        xlab = "",
                        yaxes = FALSE,
                        xaxes = FALSE
                        ){
  if(is.numeric(x)) x <- round(x, 1)
  if(is.numeric(y)) y <- round(y, 1)
  par(mar = mar)
  plot(0,
       ylim = ylim,
       xlim = xlim,
       main = "",
       xlab = "",
       ylab = "",
       axes = FALSE,
       )
  if(xaxes){
    axis(side = 1,
         las = 1, 
         lwd = 2, 
         mgp = c(2, 1, 0), 
         cex.axis = 1,
         col = colvect("grey22", alpha = 0.9))
    }
  if(yaxes){
    axis(side = 2,
         las  = 2, 
         lwd  = 2, 
         mgp  = c(1, 0.75, 0), 
         cex.axis = 1,
         col = colvect("grey22", alpha = 0.9))
    }
  grid(nx = NULL, # X-axis divided in two sections
       ny = NULL, # Y-axis divided in three sections
       lty = 2, 
       col = colvect(c("gray69"), alpha = 0.5), lwd = 1)
  box(which = "plot", 
      lty = "solid", 
      lwd = 3, 
      col = colvect("grey22", alpha = 0.9))
  title(main = main,
        cex.lab = 2,
        line= line,
        adj = adj)
  title(ylab = ylab, cex.lab = 1.5, line = 2.5)
  title(xlab = xlab, cex.lab = 1.5, line = 2.5)
}

# ------------------------------------------------------------------------------
# # input is a raster
# chl_fronts = function(ras,
#                       downsize = 10,
#                       I = 2){
#   ras  = raster::flip(ras, direction = "x")
#   thresh = median(ras, na.rm = TRUE) + mad(ras, na.rm = TRUE)*I
#   
#   idx  = which(values(ras) == 1)
#   
#   e    = extent(ras)
#   s    = dim(ras)
#   lons = seq(from = e[1], to = e[2], length = s[1]) 
#   lats = seq(from = e[3], to = e[4], length = s[2]) 
#   grid = pracma::meshgrid(lons, lats)
#   fronts = data.frame(lons = grid$X[idx], lats = grid$Y[idx], value = ras[idx])
#   idx = seq(1, nrow(fronts), downsize)
#   fronts = fronts[idx, ]
#   fronts
# }

# x is a single row data frame with column sdate and edate
# ras is a raster to be cut 
durationsnip = function(x,
                        ras) {
  # subset time
  t = getZ(ras)
  sdate = x$sdate
  edate = x$edate
  ind_t = which(t > sdate & t < edate)
  indx_bool = (t > sdate & t < edate)
  x = subset(x, ind_t)
  t = subset(t, indx_bool)
  x = setZ(x, z = t, name = "time")
  x
}

bloom_snip = function(x,
                     ras) {
  sdate = x$sdate
  edate = x$edate
  # subset time
  t = getZ(ras)
  
  start = which.min(abs(t - sdate))
  end   = which.min(abs(t - edate))
  ind_t = start:(start+4)
  #ind_t = which(t > sdate & t < edate)
  #indx_bool = (t > sdate & t < edate)
  idx_boo = is.element(t, t[ind_t])
  ras = subset(ras, ind_t)
  t   = subset(t, idx_boo)
  ras = setZ(ras, z = t, name = "time")
  ras
}

# fronts = function(blooms, signal){
#   # input is a raster
#   temp = function(layer,
#                   boo,
#                   downsize = 10,
#                   I = 2){
#     layer = raster::flip(layer, direction = "x")
#     boo = raster::flip(boo, direction = "x")
#     #thresh = median(signal, na.rm = TRUE) + mad(signal, na.rm = TRUE)*I
#     
#     idx  = which(values(boo) == 1)
#     
#     e    = extent(layer)
#     s    = dim(layer)
#     lons = seq(from = e[1], to = e[2], length = s[1]) 
#     lats = seq(from = e[3], to = e[4], length = s[2]) 
#     grid = pracma::meshgrid(lons, lats)
#     fronts = data.frame(lons = grid$X[idx], lats = grid$Y[idx], value = layer[idx])
#     idx = seq(1, nrow(fronts), downsize)
#     fronts = fronts[idx, ]
#     fronts
#   }
#   
#   chlb_l = list()
#   chla_l = list()
#   for(i in 1:dim(blooms)[3]) chlb_l[[i]] = blooms[[i]]
#   for(i in 1:dim(signal)[3]) chla_l[[i]] = signal[[i]]
#   
#   mapply(temp, boo = chlb_l, layer = chla_l, SIMPLIFY = FALSE)
# }

fronts = function(ras,
                  downsize = 10,
                  I = 2){
  e    = extent(ras)
  ras  = t(ras)
  ras  = raster::flip(ras, direction = "x")
  extent(ras) = e
  
  thresh = median(ras, na.rm = TRUE) + mad(ras, na.rm = TRUE)*I
  idx  = which(values(ras) > thresh)
  
  e    = extent(ras)
  s    = dim(ras)
  lons = seq(from = e[1], to = e[2], length = s[1]) 
  lats = seq(from = e[3], to = e[4], length = s[2]) 
  grid = pracma::meshgrid(lons, lats)
  fronts = data.frame(lons = grid$X[idx], lats = grid$Y[idx], value = ras[idx])
  idx = seq(1, nrow(fronts), downsize)
  fronts = fronts[idx, ]
  fronts
}

# input is a boolian raster layer of 0/1 
# output is a data frame with only high values included
# Downlsize reduces the size of the data set
# I may like to simultaniously index the chl signal as well
chl_fronts = function(blooms,
                      signal,
                      downsize = 10){
  
  e    = extent(signal)
  signal  = t(signal)
  signal  = raster::flip(signal, direction = "x")
  extent(signal) = e
  # 
  e    = extent(blooms)
  blooms  = t(blooms)
  blooms  = raster::flip(blooms, direction = "x")
  extent(blooms) = e
  
  idx  = which(values(blooms) == TRUE) # == TRUE
  
  e    = extent(blooms)
  s    = dim(blooms)
  lons = seq(from = e[1], to = e[2], length = s[1]) 
  lats = seq(from = e[3], to = e[4], length = s[2]) 
  grid = pracma::meshgrid(lons, lats)
  # using the blooms index to subset the signal values
  fronts = data.frame(lons = grid$X[idx], lats = grid$Y[idx], value = signal[idx])
  idx = seq(1, nrow(fronts), downsize)
  fronts = fronts[idx, ]
  fronts
}

# use the apply function to apply the calc mean function for every 8 layers

avestack = function(ras, by = 8, fun){
  t = getZ(ras)
  s      = dim(ras)
  idx_8d = rep(1:ceiling(s[3]/8), 8)
  idx_8d = sort(idx_8d)
  rem    = abs(s[3] - length(idx_8d))
  idx_8d = idx_8d[1:(length(idx_8d)-rem)]
  idx_og = 1:s[3]
  t_idx  = unique(idx_8d)
  idx    = data.frame(idx_8d = idx_8d, idx_og = idx_og)
  idx$idx_8d = as.factor(idx$idx_8d)
  idx = split(idx, idx_8d)
  
  # subset and average every eight days
  tempset = function(x, ras) ras[[x$idx_og]]
  days = lapply(idx, FUN = tempset, ras = ras)
  days = lapply(days, FUN = calc, fun = fun, na.rm = TRUE)
  days = brick(days)
  days = setZ(days, z = t[t_idx], name = "time")
  days
  }

# Writing this as a function to take a date range, a chl anomaly signal, 
# and output an area time-series

# Input is 3D chla raster output is time series vector of bloom area
bloom_area = function(b){
  t    = getZ(b)
  rr   = reclassify(b, cbind(0,NA))
  a    = raster::area(rr)
  temp = raster::mask(a, rr)
  
  km2  = cellStats(temp, stat = "sum", na.rm = TRUE)
  data.frame(area = as.numeric(km2), time= t)
}

# input x is a raster of raw chl
# inpur x is a raster of 0/1 bloom non-bloom
bloom_mag = function(x, b){
  t = getZ(x)
  # Area time series for duration 
  rr   = reclassify(b, cbind(0,NA))
  # find area of each cell + mask cells that matter
  temp = raster::mask(x, rr)
  mag  = cellStats(temp, stat ="max", na.rm = TRUE)
  data.frame(mag = as.numeric(mag), time= t)
}  


# 
bool = function(x){
  u <- calc(x, fun = median, na.rm = TRUE)
  o <- calc(x, fun = mad, na.rm = TRUE)
  boo <- x > (u + o)
  extent(boo) <- extent(x)
  boo <- setZ(boo, z = getZ(x), name = "time")
  boo
}

vectorize  <- function(x) {
  sdate <- getZ(x)
  # x = raster::flip(x, direction = "x")
  # x = raster::flip(x, direction = "y")
  # 
  e = extent(x)
  x = t(x)
  extent(x) = e
  # 
  x     <- rasterToPoints(x)
  x     <- data.frame(x)
  colnames(x) <- c("lon", "lat", as.character(sdate))
  x     <- reshape2::melt(x, id.vars = c("lat", "lon"))
  colnames(x) <- c("lats", "lons", "time", "val")
  x
}

tsect <- function(x, y, z, xreach = 1, yreach = 1, xlen = 120, ylen = 40){
  #make a max min vector of sla and fsle
  coord = c(max(x, na.rm = TRUE), min(x, na.rm = TRUE), 
            max(y, na.rm = TRUE), min(y, na.rm = TRUE))
  
  # use maxmin vector to create fake x, y vectors (downsized) as meshgrid input
  y_vec <- seq(from = coord[4], to = coord[3], length.out = ylen) 
  # may need to invert to be same length 
  x_vec <- seq(from = coord[2], to = coord[1], length.out = xlen)
  xy_grid <- meshgrid(x_vec, y_vec)
  
  #inisilize a matrix of dim fs_grid[1] filled with NA values
  dims <- dim(xy_grid[[1]])
  z_grid <- matrix(data = NA, 
                   nrow = dims[1], 
                   ncol = dims[2], 
                   dimnames = NULL)
  
  for(iy in 1:dims[1]) {
    for(ix in 1:dims[2]){
      # where in the df is the difference greater than the units
      box_x <- which(abs(x - xy_grid[[1]][iy, ix]) <= xreach)
      box_y <- which(abs(y - xy_grid[[2]][iy, ix]) <= yreach)
      # I think the grids are dif sizes and should be subet differently
      #index vector of both cox_sla and box_fsle as one
      #box <- sort(match(box_y, box_x))
      
      # I think this is the correct way to do this
      box <- box_x[box_x %in% box_y]
      
      z_grid[iy, ix] <- mean(z[box], na.rm = TRUE)
    }
  }
  
  list(z_grid, y_vec, x_vec)
}

```

load data
```{r}
lons = c(-175, -125)
lats = c( 15,   40)

# I need to make sure I'm not saving a fuck tun of files
# I'm uploading the large data set for the anomaly calculation
chl = loadchl(url = "https://coastwatch.noaa.gov//erddap",
              id  = "noaacwNPPN20S3ASCIDINEOFDaily",
              lat = lats,
              lon = lons,
              parameter = c("all"),
              sdate = as.Date("2018-07-01"),
              edate = as.Date("2018-11-30"),
              large = FALSE)

# This needs to be a relative path so it will work via git hub
fsle = load_nc(path = "C:\\Users\\james\\Desktop\\jamieslife\\data\\infiles\\case_study\\",
               patt = "fsle_po_2018.nc")

gc()
```

correct oreantation
```{r}
oreant = function(ras, flip = NULL, t1 = FALSE, t2 = FALSE){
  e    = extent(ras)
  time = getZ(ras)
  if(t1) ras = raster::t(ras)
  if(!is.null(flip)) ras = raster::flip(ras,  direction = flip)
  if(t2) ras = raster::t(ras)
  extent(ras) = e
  ras = setZ(ras, z = time, name = "time")
  ras
  }

fsle = oreant(fsle, flip = "x", t2 = TRUE)
chl  = oreant(chl, t1 = TRUE)
```

```{r}
cmap = calc(chl, fun = mean, na.rm = TRUE)
fmap = calc(fsle, fun = mean, na.rm = FALSE)
plot(cmap)
plot(fmap)
```

Crop because FSLE is not downloaded right
```{r crop}
fix_fsle = function(x) {
  time = getZ(x)
  e = extent(x) - c(360, 360, 0 ,0)
  x  = x * -1
  extent(x) = e
  x = setZ(x, z = time, name = "time")
  x
  }

fsle = fix_fsle(fsle)

e = extent(-165, -135, 17, 35)
fsle = raster::crop(fsle, e)
chl  = raster::crop(chl,  e)

gc()
```

Calculate a CHL anomaly and index bloom values
```{r}
#chla = anomalize(ras = chl, detrend = FALSE)
#gc()
```

Make FSLE and CHL them the same time domain. Make FSLE same temporal resolution as CHL
```{r}
sdate = max(min(getZ(chl)), min(getZ(fsle)))
edate = min(max(getZ(chl)), max(getZ(fsle)))
fsle = timesnip(fsle, sdate = sdate, edate = edate)
chl  = timesnip(chl,  sdate = sdate, edate = edate)

# match all the dates
tc = getZ(chl)
tf = getZ(fsle)
tf = as.numeric(tf)
tc = as.numeric(tc)

# subset just FSLE to CHL time
idx  = which(is.element(tf, tc))
tf   = subset(tf, is.element(tf, tc))
fsle = raster::subset(fsle, idx)
fsle = setZ(fsle, z = as.Date(tf), name = "time")

rm(tc, tf, idx, e)
gc()
```

remove coastal effects
```{r}
chl  = bufcoast(chl, 
                region = "Hawaiian Islands", 
                path = "../data/USMaritimeLimitsAndBoundariesSHP")
fsle = bufcoast(fsle, 
                region = "Hawaiian Islands", 
                path = "../data/USMaritimeLimitsAndBoundariesSHP")
gc()
```

find fronts
```{r}
# chlb_l = list()
# chla_l = list()
chl_l  = list()
fsle_l = list()
for(i in 1:dim(chl)[3]) chl_l[[i]] = chl[[i]]
for(i in 1:dim(fsle)[3]) fsle_l[[i]] = fsle[[i]]

chl_points  = lapply(chl_l, fronts, I = 0, downsize = 1)
fsle_points = lapply(fsle_l, fronts, I = 2, downsize = 1)

# FSLE is still negative if...
# Error in seq.default(1, nrow(fronts), downsize) : 
# wrong sign in 'by' argument
```

```{r}
# removes NA values and values less than 0.05
pretty = function(x, thresh = 0.05) {
  x = subset(x, !is.na(value))
  x = subset(x, value > thresh) 
  x 
  }

chl_points = lapply(chl_points, FUN = pretty)
```

function for plotting in animation loop
```{r}
blooms_fronts = function(bloom, currents, 
                         xaxes = FALSE, 
                         yaxes = FALSE, 
                         main = "",
                         xlab = "",
                         ylab = "",
                         wdmap = getMap(resolution = "high")) {
  
  #range01 = function(x){(x-min(x))/(max(x)-min(x))}
  bloom$value = scale(bloom$value, from = 0.05, to = 1)
  
  #bloom$value = range01(bloom$value)
    
  image(currents, 
        col = gray.colors(10, start = 1, end= 0.5, gamma = 1),
        axes = FALSE,
        ylab = "",
        xlab = "")
  if(xaxes) {
    axis(side = 1,
    #at = at,
    #labels = labels,
    las = 1, 
    lwd = 2, 
    mgp = c(2, 1, 0), 
    cex.axis = 1.25,
    col = colvect("grey22", alpha = 0.9))}
  if(yaxes){
    axis(side = 2,
    las  = 2, 
    lwd  = 2, 
    mgp  = c(1, 0.75, 0), 
    cex.axis = 1.25,
    col = colvect("grey22", alpha = 0.9))}
  title(main = main,
        cex.main = 1.75,
        line = -1.5,
        adj = 0.03)
  title(ylab = ylab, cex.lab = 1.5, line = 2.5)
  title(xlab = xlab, cex.lab = 1.5, line = 2.5)
  box(which = "plot",
        lty = "solid",
        lwd = 3,
        col = colvect("grey22", alpha = 0.9))
  points(bloom$lons, 
         bloom$lats, 
         col = colvect(rep("#003300", length(bloom$value)), alpha = bloom$value),
         pch = 20,
         cex = 1)
  plot(wdmap, 
     xlim = e[1:2], 
     ylim = e[3:4], 
     asp = 1, 
     bg = "white", 
     border = "black", 
     col = "pink", 
     add = TRUE,
     lwd = 2)
}

```

```{r, fig.width = 10, fig.height = 8}
blooms_fronts(bloom = chl_points[[1]], 
              currents = fsle[[1]], 
              yaxes = TRUE, 
              main = as.character(getZ(fsle[[1]])),
              ylab = "Latitude",
              xlab = "Longitude",
              xaxes = TRUE)
```

Plotting in an animation loop to make GIF
```{r, fig.width = 10, fig.height = 8}
library(animation)
e = extent(chl)
t = getZ(chl)
day = as.character(yday(t))
s = dim(fsle)
wdmap = getMap(resolution = "high")

ani.record(reset = TRUE)
for(i in 1:s[3]){
  blooms_fronts(bloom = chl_points[[i]], 
                currents = fsle[[i]], 
                yaxes = TRUE, 
                main = as.character(getZ(fsle[[i]])),
                ylab = "Latitude",
                xlab = "Longitude",
                xaxes = TRUE,
                wdmap = wdmap)
   ani.record()
   dev.off()
   }

oopts = ani.options(interval = 0.1, ani.width = 750, ani.height = 600)
saveGIF(ani.replay())
ani.record(reset = TRUE) # clear it
```

















































