---
title: "Homework 2"
author: "Jamie Ash"
date: "2022-09-01"
output: pdf_document
---

**Question 1.** Complete the following definitions:

**Definition 1.** An integer n is even if it can be divided by two and the 
result is an integer. 

$$
\frac{n}{2} = i
$$

Where n is some number, and i is an integer. 

**Definition 2.** An integer m is odd if we can add one then divide by two and 
the result is an integer. 

$$
\frac{(n+1)}{2} = i
$$
Where $n$ is some number, and $i$ is an integer. 

**Question 2.** Use your definitions to prove the following statement.

  **Proposition 3.** If n is an even integer then $n^2$ is an even integer.

If n is an even integer then $n = 2i$, where i is some integer. Then n^2 is an 
even integer if $n^2/2 = i$. 

When we substitute $2i$ for $n$ in $n^2/2 = i$ we get the following.

$$
\frac{(2i)^2}{2} = i \tag{1}
$$
We rearrange the equation to be...

$$
\frac{1}{2}(2i)(2i) \tag{2}
$$
Then if we factor out the 2 we get...
$$
(i)(2i) \tag{3}
$$
When two integers are added or multiplied the result is an integer. So the 
result of $(i)(2i)$ is always an integer, and $n^2$ is always an even number. 

This can be extended to $n^x$ where $x$ is some natural number. So step 2 would 
become:

$$
i = \frac{1}{2}(2i)(2i)... \\
i = (i)(2i)...
$$
Similarly $(i)(2i)...$ is entirely composed of integers being multiplied by one 
another, so the result is an integer, and $n^x$ is even.





























