---
output: pdf_document
---

Slide 1: Title slide
*Hello, my name is Jamie Ash. I'm  Masters student in Angel White's lab. My thesis project aimed at characterize the chlorophyll blooms that are occurring in the North East Pacific Subtropical Gyre.  

Slide 2-5: Monthly Bloom plots
*These blooms occur both around St. Aloha and along 30N line of latitude depicted here this map that shows the area just north of the Hawaiian islands.  
*There is a wealth of literature on these blooms.  
*Leading hypothesis are:  
    internal breaking waves  
    convergent surface currents  
    nutrent upwelling at the subtropical front caused by ekman transport   
    (sub)mesoscale eddy dynamics  

Slide 6: Objectives  
* First we characterize the magnitude, frequency, and geographic location of CHL blooms. We do this using an updated bloom threshold on the CHL anomaly that we calculate using an STL filter.  
* We then use a cluster analysis using FSLE and SLA satellite fields to determine the association of (sub)mesoscale features with the CHL blooms. This is done to identify the potential physical drivers of these blooms.   
* Finally we hope to present a case study of a bloom from each study region to better understand the time-resolved change in phytoplankton biomass across the lifespan of the blooms.   

Slide 7: HPLC against Satellite CHL Comparison and CHL Climatologies  
* To start off I make a comparison between the HPLC bottle samples to the CHL satellite signal.   
* HPPLC are the gold standard for measuring CHL pigment in water. Ideally there would be a near 1:1 fit between the two (dashed line).  
* Although the slope is 0.5 we do find that the fit is significant. We find this to be good enough.   
* The CHL satelite is largely influenced by the uper 25m of ocean, but the CHL maximum consistently occurs around 125m   
* The seasonal signal is driven by photo-acclimation. In the winter individual phytoplankton cells produce more CHL to accommodate the lower light levels. So an increase in CHL signal is not directly corelated to an increase in cell growth or count (ie a bloom)  

Slide 8: Climatology of the STL filtered CHL sat residuals: 2002-2019  
* The first step of the analysis was to address the seasonal signal that is driven by photo-acclimation.   
* To address this we calculate a CHL anomaly that removes the seasonal trend, and captures the CHL blooms in the late summer.  
* Climatology of the STL filtered CHL sat residuals: 2002-2019  
* We feel it does a better job of capturing these late summer CHL blooms.  
* You can see it removes the MASS Island effect and the CHL Maximum Front pretty well.  

Slide 9-12: Monthly Composites Bloom Frequency  
* The classic bloom threshold for this region is a blanket 0.15mg/m^3   
* The redefined bloom threshold is the median plus the MAD of the CHL anomoly previously shown. Outlier  
* In simple terms the bloom values are the outliers of the CHL anomaly   
* Even years with few blooms (2016) still have blooms associated with eddies the size of big island  

SLide 13: Summary table of late summer CHL blooms in the NEPSG  
* I generated a summary statistics table for each bloom each year.   
* The last for about 1-4 months,   
* Over hundreds of thousands of kilometers^2,   
* their magnitude is well above 0.15 bloom threshold  
* Occur at near St. ALOHA and 30N at equal frequecny   

Slide 14: (Sub)mesoscale Background  
* I'm interested in how submesoscale and mesoscale regions are correlated to CHL blooms.   
* Define Mesoscale/submesoscale regions.   
* I identify these regions using a cluster analysis on SLA and FSLE satellite products  
* SLA is the SSH with the climatological/seasonal mean subtracted out  
* High FSLE represents high stretching. used to identify fronts.   
  
Slide 15: Comparison of k-means (Sub)mesoscale Identification and AVISO Eddy Atlas  
* This is a visualization of the SLA (red-blue) and FSLE (grey) fields as well as the submesoscale regions (bottom figure).  
* The SLA and FSLE fields (top figure) are the inputs to the k-means cluster analysis and the (sub)mesoscale regions are the outputs of the cluster analysis.  
* What we're really interested in is how these CHL blooms (snapshot in top figure) a line with the (sub)mesoscale regions.   

Slide 16: Kmeans cluster analysis of (sub)mesoscale regions at St. ALOHA  
* This is the same concept I just showed, but gives more insight into how the cluster analysis works.   
* The x-axis is SLA and the y-axis is FSLE (inputs to the cluster analysis) and the color is the group factor (output of the cluster analysis)  
* each of these points is associated with a lon/lat/datetime and all the cluster analysis sees is the paired SLA and FSLE values and the output is a factor between 1-4 (colors).   
* Each point is associated with a CHL value, and we're interested in how the CHL bloom values fall into the different (sub)mesoscale groups.   
* As an exploratory step I calculate the percent association of the Bloom values with the (sub)mesoscale regions.   
 
Slide 17: (Sub)mesoscale Percent Association to CHL Anomalies  
* I represent the results as percent association to each submesoscale region. The rows sum to 100%  
* For example, in 2018 the CHL blooms was very much so associated with positive mesoscale features. The difference from the background field is 3%.   
* I'm primarily using these results to get a general overview of what is going on within each bloom year, as well as to inform a case study.   

Slide 18: Case Study: Time-resolved (sub)mesoscale and CHL interactions: 2018  
* For the case Study I would like to address the time resolved change in CHL. What's happening from the onset to the demise of the blooms.   
* I'm considering a GAM because it can handle spatially and temporally auto-correlated data.   
* To do this I used a geneelized additive model (GAM) to correlate the (sub)mesoscale regions to CHL satelite signal across the lifespan of the bloom  
* Again in 2018 the CHL blooms was very much so associated with positive mesoscale features, and submesoscale features  
* This could indicate that this bloom was associated with regions of downwelling. Producing an environment where nitrogen fixing phytoplankton could thrive (bloom).  

Slide 19: Spatio-temporal evolution of the 2007 bloom  

Slide 20: Conclusion   

Slide 21: Acknowledgments  






















