---
title: "figure_methods"
author: "Jamie Ash"
date: "2022-08-19"
output: pdf_document
---

# Pre-Processing ---------------------------------------------------------------

## General Processing

The CZZ boarders where used as a mask to remove the coastal effects in the CHL 
SLA, and FSLE data sets. Then a CHL anomaly was calculated by removing the 
seasonal effects and long term climatologic effects from the raw CHL satellite 
signal. CHL blooms values where identified as any point greater than the median
plus the MAD per grid cell (across time) of the CHL anomaly. 

## Figure 4: HPLC against Satellite CHL Comparison and CHL Climatologies

Comparison of High-pressure Liquid Chromatography (HPLC) bottle samples against 
the GlobColor CHL1 Lm3 satellite product. The generalized linear regression 
(family = gamma) gives an $r^2$ value of $0.454$ with a significant fit 
($p < 0.05$). Figure b) a box plot of the average monthly CHL satellite signal 
across the 18 years of data. The light grey boxes are for the region at 30N, and 
the dark grey box is for the region around Stn. ALOHA.

**Discussion:** Done

# Characterizing CHL blooms ----------------------------------------------------

## Table 1: Summary table of late summer CHL blooms in the NPSG

**Methods:** To identify when particularly large blooms occurred in an 
autonomous way, an STL filter was applied to the daily averaged time series of 
the CHL satellite data set. Bloom time periods were identified as any period 
above the mean and standard deviation of the residuals of the STL filter. 
Periods where the bloom received for shorter than 7 days where ignored and 
blooms that lasted longer than 14 days where chosen. Alternatively, start and 
end dates of the blooms where chosen manualy by viewing weekly chlorophyll maps. 
This proved to be more effective than a over engineered autonomous bloom 
identification process.

The bloom duration was found by subtracting the end from the start date. The 
magnitude was defined as the maximum value the CHL satellite signal reached at 
any point during the blooms. The bloom area was calculated as the maximum area 
the bloom reached. The center longitude and latitude locations where found by 
taking the average longitude and latitude location of each bloom point on the 
day the bloom reached it's maximum area. To mitigate the effects of clouds, the 
weekly chl product was used to find the bloom area and center. Blooms that 
occurred for less than two weeks where excluded.

## Figure 1: Monthly Composites of $CHL_{sat}$ in the NPSG

**Methods:** To generate the monthly thumbnail plots of bloom values, monthly 
composites of CHL data were used, and bloom values from the late summer months 
from June - October were plotted.  

## Figure 2: Bloom centers and maximum area

**Methods:** Bloom center from table 1 where plotted along with their maximum 
area represented as circles. The area of each circle is equal to the maximum 
area each amorphic bloom reached.

## Figure 3: Bloom duration and day of year

**Methods:** Bar plot of the bloom duration for all summer to fall blooms that 
occur between 2003-2021. Start and end date of each bloom (table 1) found using 
an STL filter. The length of each bar is equal to the duration described in 
table 1, as well as the start date of each bloom. The grey center line is the 
date each bloom reached it's maximum magnitude. Blooms lasting less than 14 days
were omitted. 

**Discussion:** While meso-scale blooms the size of Hawaii (big island) occur 
every year, blooms larger than $10,000 km^2$ occur semi-annually. These blooms 
tend to last approximately 20 - 100 days. A few blooms (2007, 2015, 2020) begin 
in the late summer, August - September, but persist until the winter where they 
are engulfed by the subtropical CHL front, making a true end date difficult to 
distinguish. Conversely some blooms notably 2005 and 2019 (Toyoda explains 
these), begin as the subtropical CHL front recedes and a true start date is 
difficult to distinguish. In some cases, 2007 and 2020 multiple large blooms 
occur in a single year. Interestingly, the maximum magnitude of each bloom 
occurs towards the XXXX or the bloom's lifespan. 

Bloom magnitudes range from 0.17 - 3.00, with a median value of $0.67 [mg/m^2]$, 
approximately $\times 4.5$ the background $1-1.5 [mg/m^3]$. Some of the stronger
blooms occurred along 32N in 2011, 2007, and 2020. The magnitude of the raw 
chlorophyll satellite signal does not taking into account the northward 
chlorophyll gradient. When considering the chlorophyll anomaly's maximum
magnitude that does correct for the northward chlorophyll gradient, the years
XXXX, XXXX had the strongest blooms which occurred at Stn. Aloha and 30N 
respectively. 

The area of the blooms range from $1.37 \times 10^4 [km^2]$ in 2012 to  
$9.43 \times 10^5 [km^2]$ in 2018. This excludes blooms less than 
$1 \times 10^5 [km^2]$ and those that are engulfed by the subtropical 
chlorophyll front. The blooms appear to cluster in three locations, that is, 
near Stn. ALOHA at [25N, -152W], at approximately [32N, 160W] and [32N, 140W]. 

# 2018 Case Study --------------------------------------------------------------

## Figure 6:  k-means cluster analysis of (sub)mesoscale regions

K-means cluster analysis (method = euclidean distance, k = 4, scale = 0-1) 
applied to the FSLE, and SLA fields at St. ALOHA during the late summer months 
(July-October) of 2018. The cluster analysis groups each data point into one of 
four (sub)mesoscale regions: mesoscale positive, mesoscale negative, 
submesoscale, and mixed regions.

**Methods:** To group the parameters into (sub)mesoscale categories, we take the
approach outlined by Gou et al. (40) where k-means clustering algorithm (k = 4) 
is used to group the SLA and FSLE data points into one of four physical regions 
based on the clusters centroid location in FSLE-SLA space (Figure 4) i.e. 
positive mesoscale (anti-cyclonic eddies), negative mesoscale (cyclonic eddies), 
sub-mesoscale (fronts) and mixed. 

We applied the k-means cluster analysis to the daily SLA and FSLE fields within 
the study region across the lifetime of the 2018 bloom: 2018-07-28 to 2018-10-15 
(Figure 5). Each group, 1-4, was assigned it's respective (sub)mesoscale region 
i.e. anti-cyclonic eddy regions (blue), cyclonic eddy regions (orange), frontal 
regions (yellow) and mixed regions (purple). 

**Discussion:** 

## Figure 5: Two late summer CHL blooms relationship to fronts and eddies

Plankton bloom for 2019 and 2020 overlaid by FSLE and eddies. 

**Methods:** A weekly layer of the CHL satellite product that occurred closest 
to the date that the bloom reached it's maximum area was subset for the 2020 
bloom and the 2019 bloom. Only the bloom values where plotted. Cyclonic and 
anti-cyclonic eddies as well, as FSLE frontal features where overlaid on the CHL 
satellite product. Both cyclonic and anti-cyclonic eddies are plotted as black 
lines. 

**Discussion:** Both blooms appear to be associated with frontal features with 
little apparent association to mesoscale eddies.

## Figure 7: Spatio-temporal evolution of the 2018 bloom

8 day composites showing the start and demise of the 2018 bloom in the NSPG. 
Bloom values are chosen using the CHL anomaly. Strong frontal features  from 
FSLE satellite data are shown as black lines. Day of the year is shown in the 
top left corner of each plot.

**Methods:** The 8-day CHL product was used to plot the weekly layers of the 
bloom values across the lifespan of the 2018 bloom. Strong frontal features i.e. 
FSLE values greater than the mean plus the standard deviations  of the daily 
FSLE field were over laid on the bloom points.

**Discussion:** 

## Figure 8: Satellite-based time series of the 2018 bloom

Time-series progression of the onset and demise of the 2018 bloom in the NPSG. 
Black and grey lines (95% confidence interval) are a GAM smoother. Figure a) 
shows the surface, figure b) shows the biomass, and figure c) shows the depth 
integrated CHL concentration.

**Methods:** 

**Discussion:** 

## Figure 9: (Sub)mesoscale features across the lifespan of the 2018 bloom

Timeseries of bloom percent association (deviation from the background) of bloom 
values to cyclonic eddies, anti-cyclonic eddies and frontal features. Percent 
association is the percent of each (sub)mesoscale region’s area that is 
associated with a bloom feature.

**Methods:** The total percent of bloom values in the CHL anomaly field that 
coincided (spatially and temporarily) with each (sub)mesoscale region was 
calculated at daily intervals and represented as a time-series (Figure (9). To 
find the effect each region had on the bloom association to each (sub)mesoscale 
region, the daily background signal was subtracted from each time-series. The 
background signal was calculated by finding the total percent by day of points 
in the CHL anomaly fields that are considered bloom values. 



















